name: 📚 Documentation Improvement
description: Suggest improvements to documentation, examples, or guides
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ProcTap's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - API Reference / Docstrings
        - Code Examples
        - Tutorial / Guide
        - Installation Instructions
        - Troubleshooting Guide
        - CLAUDE.md (Developer Guide)
        - Type Stubs (.pyi files)
        - Inline Code Comments
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: Describe what's missing, unclear, or incorrect in the documentation
      placeholder: |
        The documentation doesn't explain how to...
        The example code is confusing because...
        The installation instructions are missing...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: |
        - File: README.md, section "Basic Usage"
        - Line 42 in src/proctap/core.py docstring
        - examples/windows_basic.py
      render: markdown
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (If Applicable)
      description: Quote or paste the current documentation that needs improvement
      placeholder: |
        Currently says:
        "Use ProcessAudioCapture to capture audio."
      render: markdown

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Improvement
      description: What should the documentation say instead?
      placeholder: |
        Should say:
        "ProcessAudioCapture captures audio from a specific Windows process by PID.
        Example: `tap = ProcessAudioCapture(pid=12345)`"
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - Beginners (new to ProcTap)
        - Intermediate Users
        - Advanced Users / Contributors
        - All Users
    validations:
      required: true

  - type: checkboxes
    id: doc-scope
    attributes:
      label: Documentation Scope
      description: What aspects should the improved documentation cover?
      options:
        - label: Clear explanation of concepts
        - label: Working code examples
        - label: Common pitfalls / gotchas
        - label: Performance considerations
        - label: Type hints and signatures
        - label: Error handling
        - label: Platform-specific notes (Windows versions)
        - label: Integration examples (Discord, etc.)

  - type: textarea
    id: example-code
    attributes:
      label: Example Code (Optional)
      description: If you're suggesting a code example, provide it here
      placeholder: |
        ```python
        from proctap import ProcessAudioCapture

        # Example demonstrating the concept
        ```
      render: python

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues / Questions
      description: Link to related issues, discussions, or questions
      placeholder: |
        - Related to #123
        - Users asked about this in Discussion #456
        - Stack Overflow question: https://...

  - type: checkboxes
    id: languages
    attributes:
      label: Language / Translation
      description: Does this involve translation or localization?
      options:
        - label: English documentation improvement
        - label: Add Japanese translation
        - label: Add other language translation
        - label: Fix grammar / spelling

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Can you help improve the documentation?
      options:
        - label: I can submit a PR with the documentation changes
        - label: I can write example code
        - label: I can review/proofread changes
        - label: I can help translate

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the documentation improvement
      placeholder: Screenshots, links to good documentation examples from other projects, etc.
