name: ✨ Feature Request
description: Suggest a new feature or enhancement for ProcTap
title: "[Feature]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be useful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like ProcTap to support...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered... / Another approach might be...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        I want to use ProcTap for...
        This feature would enable me to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example API (Optional)
      description: If applicable, show what the API might look like
      placeholder: |
        ```python
        from proctap import ProcessAudioCapture

        # Example of how the feature might work
        tap = ProcessAudioCapture(pid=1234, new_feature=True)
        ```
      render: python

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Audio Capture (core functionality)
        - API Design (usability, ergonomics)
        - Performance (speed, latency)
        - Format Support (sample rates, channels)
        - Integration (Discord, streaming, etc.)
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...
