name: ⚡ Performance Issue
description: Report performance problems or suggest optimizations
title: "[Performance]: "
labels: ["performance"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a performance issue! Please provide detailed information to help us optimize ProcTap.

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: The audio capture is experiencing high latency / CPU usage / memory usage...
    validations:
      required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: Performance Issue Type
      description: What type of performance issue are you experiencing?
      options:
        - High CPU Usage
        - High Memory Usage
        - Audio Latency / Delay
        - Dropped Frames / Buffer Underruns
        - Slow Startup Time
        - Other
    validations:
      required: true

  - type: textarea
    id: measurements
    attributes:
      label: Performance Measurements
      description: Provide quantitative measurements if possible
      placeholder: |
        - CPU Usage: 45% (expected: <10%)
        - Memory Usage: 500 MB (expected: <100 MB)
        - Latency: 200ms (expected: <50ms)
        - Audio dropout rate: 5 per minute
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Start capturing from process with PID ...
        2. Monitor CPU/memory usage
        3. Observe high resource consumption after X minutes
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Provide code that demonstrates the performance issue
      placeholder: |
        ```python
        from proctap import ProcessAudioCapture

        # Code that exhibits poor performance
        ```
      render: python

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Provide detailed system information
      placeholder: |
        - ProcTap Version: 0.1.0
        - Python Version: 3.11.5
        - Windows Version: Windows 11 22H2
        - CPU: Intel i7-12700K / AMD Ryzen 9 5950X
        - RAM: 32 GB
        - Target Process: VRChat.exe / Chrome.exe
      render: markdown
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration Details
      description: What configuration are you using?
      placeholder: |
        - Sample Rate: 44.1 kHz
        - Channels: 2 (stereo)
        - Buffer Size: 10ms
        - Callback frequency: Every 20ms
      render: markdown

  - type: textarea
    id: profiling
    attributes:
      label: Profiling Data (Optional)
      description: If you've done any profiling, share the results
      placeholder: |
        Paste profiling output, flamegraphs, or performance traces here...
      render: shell

  - type: textarea
    id: optimization-ideas
    attributes:
      label: Optimization Ideas
      description: Do you have any ideas on how to improve performance?
      placeholder: |
        Possible optimizations:
        - Reduce memory allocations
        - Use larger buffers
        - Optimize threading model

  - type: checkboxes
    id: comparison
    attributes:
      label: Comparison with Alternatives
      description: Have you compared with other solutions?
      options:
        - label: The performance issue does NOT occur with system-wide capture
        - label: The performance issue does NOT occur with other audio capture tools
        - label: The issue appears to be specific to certain target processes

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the performance issue
      placeholder: Any additional information, graphs, or screenshots...
