name: 🔧 Type Hints / Async Extension
description: Suggest improvements to type hints or async functionality
title: "[Types/Async]: "
labels: ["enhancement", "types", "async"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ProcTap's type safety and async capabilities!

  - type: dropdown
    id: category
    attributes:
      label: Improvement Category
      description: What type of improvement are you suggesting?
      options:
        - Type Hints (missing or incorrect)
        - Type Stubs (.pyi files)
        - Generic Types / TypeVar
        - Async API Enhancement
        - Async/Await Pattern Improvement
        - Protocol / ABC Design
        - Type Checking with mypy
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the type hint or async improvement you're proposing
      placeholder: The `ProcessAudioCapture.read()` method is missing return type annotations...
    validations:
      required: true

  - type: textarea
    id: current-code
    attributes:
      label: Current Code
      description: Show the current code that needs improvement
      placeholder: |
        ```python
        # Current implementation
        def read(self, timeout=1.0):
            return self._backend.read()
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: proposed-code
    attributes:
      label: Proposed Improvement
      description: Show what the improved code should look like
      placeholder: |
        ```python
        # Proposed improvement
        def read(self, timeout: float = 1.0) -> Optional[bytes]:
            """Read one audio chunk (blocking).

            Args:
                timeout: Maximum time to wait in seconds

            Returns:
                PCM audio data, or None if timeout
            """
            return self._backend.read()
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: mypy-errors
    attributes:
      label: mypy Errors (If Applicable)
      description: If this addresses mypy errors, paste them here
      placeholder: |
        error: Missing return type annotation for function "read"
        error: Incompatible return value type (got "bytes", expected "None")
      render: shell

  - type: dropdown
    id: async-focus
    attributes:
      label: Async-Specific Focus (If Applicable)
      description: If this is async-related, what aspect?
      options:
        - Not async-related
        - AsyncIterator / AsyncGenerator
        - Context Manager (async with)
        - Cancellation / Cleanup
        - Backpressure Handling
        - Error Handling in Async
        - Type Hints for Async
        - Other

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: Why is this improvement needed?
      placeholder: |
        This would help because:
        - Better IDE autocomplete
        - Catch errors at type-checking time
        - Clearer API documentation
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Check all that apply
      options:
        - label: This change is backward compatible
        - label: This requires a breaking API change
        - label: This affects only type annotations (runtime unchanged)
        - label: This requires Python 3.11+ features

  - type: textarea
    id: references
    attributes:
      label: References / Examples
      description: Link to similar implementations or typing patterns in other libraries
      placeholder: |
        Similar patterns in:
        - https://github.com/...
        - PEP 484, 526, 544, etc.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Can you help implement this?
      options:
        - label: I can submit a PR with type hints
        - label: I can update .pyi stub files
        - label: I can add mypy configuration
        - label: I can write tests for type checking

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details, related issues, etc.
